let rbody =
{
    "code": 0,
    "msg": "success",
    "data": {
        "items": [
            {
                "position": 2,
                "itemid": 1,
                "shopid": 1,
                "name": "",
                "label_ids": [],
                "image": "",
                "images": [],
                "currency": "TWD",
                "stock": 0,
                "status": 1,
                "ctime": 1660726515,
                "sold": 0,
                "historical_sold": 0,
                "liked": false,
                "liked_count": 0,
                "catid": 0,
                "brand": "",
                "cmt_count": 0,
                "flag": 0,
                "cb_option": 0,
                "item_status": "normal",
                "price": 0,
                "price_min": 0,
                "price_max": 0,
                "price_min_before_discount": 0,
                "price_max_before_discount": 0,
                "price_before_discount": 0,
                "has_lowest_price_guarantee": false,
                "show_discount": 0,
                "raw_discount": 0,
                "discount": "",
                "size_chart": "",
                "tier_variations": [],
                "item_rating": {
                    "rating_star": 0,
                    "rating_count": [],
                    "rcount_with_context": 0,
                    "rcount_with_image": 0
                },
                "item_type": 0,
                "reference_item_id": "",
                "transparent_background_image": "",
                "is_adult": false,
                "badge_icon_type": 0,
                "shopee_verified": false,
                "is_official_shop": true,
                "show_official_shop_label": true,
                "show_shopee_verified_label": false,
                "show_official_shop_label_in_title": true,
                "is_cc_installment_payment_eligible": true,
                "is_non_cc_installment_payment_eligible": false,
                "show_free_shipping": false,
                "bundle_deal_id": 0,
                "can_use_bundle_deal": true,
                "bundle_deal_info": {
                    "bundle_deal_id": 0,
                    "bundle_deal_label": ""
                },
                "welcome_package_type": 0,
                "can_use_wholesale": false,
                "is_preferred_plus_seller": false,
                "shop_location": "",
                "has_model_with_available_shopee_stock": false,
                "voucher_info": {
                    "promotion_id": 0,
                    "voucher_code": "",
                    "label": ""
                },
                "can_use_cod": true,
                "is_on_flash_sale": false,
                "is_mart": false,
                "shop_name": "",
                "shop_rating": 0,
                "global_cat": { "catid": [] },
                "local_cat": {},
                "flash_sale_stock": 0,
                "fe_cat_paths": [],
                "is_service_by_shopee": false,
                "mtime": 1703484506,
                "flash_sale_ongoing_sold_count": 0,
                "global_sold_count": 0,
                "item_card_display_price": {}
            },
            {
                "position": 1,
                "itemid": 1,
                "shopid": 1,
                "name": "",
                "label_ids": [],
                "image": "",
                "images": [],
                "currency": "TWD",
                "stock": 0,
                "status": 1,
                "ctime": 1660726515,
                "sold": 0,
                "historical_sold": 0,
                "liked": false,
                "liked_count": 0,
                "catid": 0,
                "brand": "",
                "cmt_count": 0,
                "flag": 0,
                "cb_option": 0,
                "item_status": "normal",
                "price": 0,
                "price_min": 0,
                "price_max": 0,
                "price_min_before_discount": 0,
                "price_max_before_discount": 0,
                "price_before_discount": 0,
                "has_lowest_price_guarantee": false,
                "show_discount": 0,
                "raw_discount": 0,
                "discount": "",
                "size_chart": "",
                "tier_variations": [],
                "item_rating": {
                    "rating_star": 0,
                    "rating_count": [],
                    "rcount_with_context": 0,
                    "rcount_with_image": 0
                },
                "item_type": 0,
                "reference_item_id": "",
                "transparent_background_image": "",
                "is_adult": false,
                "badge_icon_type": 0,
                "shopee_verified": false,
                "is_official_shop": true,
                "show_official_shop_label": true,
                "show_shopee_verified_label": false,
                "show_official_shop_label_in_title": true,
                "is_cc_installment_payment_eligible": true,
                "is_non_cc_installment_payment_eligible": false,
                "show_free_shipping": false,
                "bundle_deal_id": 0,
                "can_use_bundle_deal": true,
                "bundle_deal_info": {
                    "bundle_deal_id": 0,
                    "bundle_deal_label": ""
                },
                "welcome_package_type": 0,
                "can_use_wholesale": false,
                "is_preferred_plus_seller": false,
                "shop_location": "",
                "has_model_with_available_shopee_stock": false,
                "voucher_info": {
                    "promotion_id": 0,
                    "voucher_code": "",
                    "label": ""
                },
                "can_use_cod": true,
                "is_on_flash_sale": false,
                "is_mart": false,
                "shop_name": "",
                "shop_rating": 0,
                "global_cat": { "catid": [] },
                "local_cat": {},
                "flash_sale_stock": 0,
                "fe_cat_paths": [],
                "is_service_by_shopee": false,
                "mtime": 1703484506,
                "flash_sale_ongoing_sold_count": 0,
                "global_sold_count": 0,
                "item_card_display_price": {}
            }
        ],
        "filteredItemIds": null
    }
}

    ;

// rbody.data.update_time = parseInt(Date.now() / 1000);
$done({
    response: {
        status: 200, headers: {
            'server': 'SGW',
            'date': new Date().toUTCString(),
            'content-type': 'application/json',
        }, body: JSON.stringify(rbody)
    }
});
